version: "3.5"

services:
  frontend:
    build:
      context: ./frontend
    container_name: currency-frontend
    restart: always
    command: bash -c "yarn start"

  backend:
    build:
      context: ./backend
    container_name: currency-backend
    restart: always
    command: bash -c "yarn start"

  postgres:
    image: postgres:10
    container_name: currency-postgres
    restart: always
    environment:
      - PGPORT=5432
      - POSTGRES_DB=currency
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - DB_HOST=postgres
  nginx:
    build:
      context: ./nginx
    ports:
      - 8000:80
    container_name: currency-nginx
    restart: always
    depends_on:
      - frontend
