version: "3.5"

services:
  frontend:
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules

  backend:
    ports:
      - 4000:4000
    restart: unless-stopped
    volumes:
      - ./backend:/backend
      - /backend/node_modules
      - /backend/dist

  postgres:
    restart: unless-stopped
    ports:
      - 5432:5432

  nginx:
    restart: unless-stopped
